## Science Grade 5

| ORExt Standard Code | Equivalent ODE Standard | Oregon Science Standard 2022 | Clarifications / Assessment Boundary 2022 | Essentialized Standard | Low (L) | Medium (M) | High (H) |
|---|---|---|---|---|---|---|---|
| S05ESS1.1 | 5-ESS1-1 | Oregon Science Standard 2022:  Oregon Alternate Academic Achievement Standard | Oregon Science Standard Clarifications/Assessment Boundary 2022:  Low (L), Medium (M), High (H) Parameters: [Clarification Statement: Emphasis is to obtain information and  L: Questions ask about the Sun being brighter than other construct an explanation on how the scale of the distance to  common objects that do not shine on their own (e.g., toy, ball, objects giving off light affects the brightness of objects (e.g.  rock). [Assessment Boundary: Assessment is limited to relative  airplanes, rockets, birds, Moon, other stars, planets). | stars is due to their relative distances from Earth.  Recognize that the Sun is brighter than other objects on Earth and in space. |  | Questions ask about the Sun being brighter than other streetlights).]  objects in sky or space that are not as bright (e.g., clouds, | Questions ask about the Sun being brighter than other stars factors that affect apparent brightness (such as stellar masses, age,  in space because it is closer to the Earth. and stage).] Science Grade 5 |
| S05ESS1.2 | 5-ESS1-2 | Oregon Science Standard 2022: Represent data in graphical  Oregon Alternate Academic Achievement Standard | Oregon Science Standard Clarifications/Assessment Boundary  Low (L), Medium (M), High (H) Parameters: [Clarification Statement: Examples of patterns could include the  difference between day and night (e.g., the Sun/daylight is position and motion of Earth with respect to the Sun and selected  associated with daytime and the Moon/stars/darkness are stars that are visible only in particular months.]   associated with nighttime), including that shadows typically [Assessment Boundary: Assessment does not include causes of  happen during the daytime. | of shadows, day and night, and the seasonal appearance of some  the difference between day and night and the appearance and stars in the night sky.  direction of shadows. | Questions use simple pictures and diagrams to ask about the | Questions use simple pictures and diagrams to ask about shadows that occur during the daytime (e.g., occurrence/direction/size of shadows based on position of Sun). | Questions use simple pictures and diagrams to ask about the Sun and the direction of shadows, including the relative amount of sunlight in different circumstances and the portion of the Earth that is daytime/nighttime (e.g., Sun lighting one side of the Earth and not the other). Science Grade 5 |
| S05ESS2.1 | 5-ESS2-1 | Oregon Science Standard 2022: Develop a model using an  Oregon Alternate Academic Achievement Standard | Oregon Science Standard Clarifications/Assessment Boundary 2022:   Low (L), Medium (M), High (H) Parameters: [Clarification Statement: Examples could include the influence of  L: Correctly identify common living organisms of Earth’s the ocean on ecosystems, landform shape, and climate; the  biosphere, including plants and animals, though not specific influence of the atmosphere on landforms and ecosystems through  names of animals or plants. [Assessment Boundary: Assessment is limited to the interactions of  minerals, mountains, volcanoes, and canyons (i.e., from the two systems at a time.]  geosphere); and air, clouds, and fog (i.e., from the atmosphere). | and/or atmosphere interact.  Earth's systems, what they are comprised of, and associated processes. |  | Correctly identify common non-living features of the Earth winds and clouds in the atmosphere. The geosphere, hydrosphere,  from various systems, restricted to: ponds, lakes, rivers, atmosphere, and biosphere are each a system.]   streams, and oceans (i.e., from the hydrosphere); rocks, | Correctly identify simple interactions among the systems (e.g., clouds (from the atmosphere) providing water (through rain) to oceans and lakes (from the hydrosphere) and to humans/animals/plants (from the biosphere); lakes/rivers (hydrosphere) providing water to humans/animals/plants (biosphere); weather (atmosphere) and water (hydrosphere) eroding mountains/rocks (through wind/rain and streams/rivers, respectively)). Science Grade 5 |
| S05ESS2.2 | 5-ESS2-2 | Oregon Science Standard 2022: Describe and graph the amounts  Oregon Alternate Academic Achievement Standard | Oregon Science Standard Clarifications/Assessment Boundary 2022:   Low (L), Medium (M), High (H) Parameters: [Clarification Statement: Emphasis is on models to organize data  L: Restricted to questions about which Earth features are made about the quantity of saltwater and freshwater in various reservoirs  of water (i.e., oceans, lakes, rivers, streams) as compared to and graph data to compare the proportions of saltwater and  common objects that are not (e.g., rock, toy, ball). [Assessment Boundary: Assessment is limited to oceans, lakes,  made of water (i.e., oceans, lakes, rivers, streams) as compared rivers, glaciers, ground water, and polar ice caps, and does not  to other natural features that are not (e.g., mountains, include the atmosphere.]  volcanoes, forests). | provide evidence about the distribution of water on Earth.  and compare the amount of water in different reservoirs on Earth. |  | Restricted to questions about which Earth features are | Restricted to comparing the relative amounts of water in various features of the hydrosphere (i.e., oceans, lakes, rivers, streams, ponds) using diagrams/graphs that reflect the relative percentages (e.g., ocean vs. lakes vs. rivers, Pacific Ocean vs. other oceans). Science Grade 5 |
| S05ESS3.1 | 5-ESS3-1 | Oregon Science Standard 2022: Obtain and combine information  Oregon Alternate Academic Achievement Standard | Oregon Science Standard Clarifications/Assessment Boundary  Low (L), Medium (M), High (H) Parameters: [Clarification Statement: Emphasis is on gathering data to construct  with exhaust, trash on ground) as compared to common an explanation on how and why the selected activity protects the  activities that obviously do not (e.g., walking, riding bike, Earth’s resources and environment for the identified region or  playing outside). [Assessment Boundary: Assessment is limited to describing how  way to protect or help the Earth (e.g., putting trash in can, communities use science ideas to protect Earth’s resources and  recycling, riding bike for transportation) as compared to environment and does not focus on cause and effect of human  common and unrelated activities (e.g., playing with a toy, impacts on the environment.]  reading a book). | Earth’s resources and environment.  communities protect or harm the Earth's environment. | Identify activities that pollute or harm the planet (e.g., car | Identify which of several simple and common choices is a | Identify which of several simple and common choices is a way to protect or help the Earth (e.g., putting trash in can, recycling, riding bike for transportation) as compared to activities that pollute or harm the Earth (e.g., pollution from a factory, littering in streams or ocean, oil spilling from a ship). Science Grade 5 |
| S05ETS1.1 | 3-5-ETS1-1 | Oregon Science Standard 2022: Define a simple design problem  Oregon Alternate Academic Achievement Standard | Oregon Science Standard Clarifications/Assessment Boundary  Low (L), Medium (M), High (H) Parameters: [Clarification Statement: A design problem must be identified  to solve?”, and are restricted to pictures and descriptions of a before solutions are developed. Solutions or designs identify the  simple problem compared to simple objects (e.g., flat bike tire criteria for success and identify limitations and constraints.]  compared to a book, bird). [Assessment Boundary: Assessment does not include limitations or  M: Questions are of a type “Which shows a (design) problem criteria based on specific process or system boundaries (e.g.  to solve?”, and are restricted to a picture and description of a limitations of scientific principles or long-term societal and  simple problem compared to other activities or situations that environmental impacts).]  are obviously not (e.g., flat tire/missing bike tire/broken toy compared to reading a book, eating food, driving a car). | and constraints on materials, time, or cost.  solve, including those related to science/engineering design. | Questions are of a type “Which shows a (design) problem |  | Questions are of the type “Which shows a (design) problem to solve?”, and are restricted to more complex problems (e.g., displaying cars/airplanes) with answers showing a possible (design) problem compared to those that are not (e.g., running out of fuel, missing a wheel/wing vs. car driving/plane flying). Science Grade 5 |
| S05ETS1.2 | 3-5-ETS1-2 | Oregon Science Standard 2022: Generate and compare multiple  Oregon Alternate Academic Achievement Standard | Oregon Science Standard Clarifications/Assessment Boundary 2022:   Low (L), Medium (M), High (H) Parameters: [Clarification Statement: Emphasis is on researching a problem  L: Questions involve simple solutions around daily activities prior to designing a solution, plan for testing to evaluate how well it  or needs (e.g., eating food - use a spoon/fork; being cold will perform under a range of likely conditions using scientific  outside - wearing a coat). [Assessment Boundary: Assessment is limited to the design process  common problems and solutions and/or the tools that solve and modeling.]  them (i.e., flat bike/car tire - use a bike pump; plants dying – use a sprinkler or hose/give plant food; nail or screw sticking out - use a hammer or screwdriver) compared to obvious non- solutions or unrelated actions (e.g., play outside, go to the park). | meet the criteria and constraints of the problem.  different problems, including those related to science/engineering design. |  | Questions involve simple solutions and are restricted to | Questions involve simple solutions and are restricted to common problems and actions and/or the tools that solve them (i.e., flat bike/car tire - use a pump; plants in a garden dying – use sprinkler or hose/give plant food; nail or a screw sticking out - use a hammer or screwdriver) compared to solutions to other similar and related problems. Science Grade 5 |
| S05LFS1.1 | 5-LS1-1 | Oregon Science Standard 2022:  Oregon Alternate Academic Achievement Standard | Oregon Science Standard Clarifications/Assessment Boundary  Low (L), Medium (M), High (H) Parameters: [Clarification Statement: Emphasis is on the idea that plant matter  plant/tree/flower needs to grow – the correct answer being comes mostly from air and water, not from the soil.]  light, water and/or air compared to things that would [Assessment Boundary: Assessment does not include photosynthesis  obviously not help growth. | growth chiefly from air and water.  Recognize that plants need light, air, and water to grow. | Questions use simple diagrams that ask what a | Questions use simple diagrams to examine if a single plant/tree/flower will grow better/worse/the same if given varying amounts of light, water and/or air. | Questions use simple diagrams to compare the (potential or actual) growth of 2-3 plants/trees/flowers when one is given an appropriate light, water and/or air, and the others are not. Science Grade 5 |
| S05LFS2.1 | 5-LS2-1 | Oregon Science Standard 2022: Develop a model to describe the  Oregon Alternate Academic Achievement Standard | Oregon Science Standard Clarifications/Assessment Boundary  Low (L), Medium (M), High (H) Parameters: [Clarification Statement: Emphasis is on the idea that matter that is  common terminology and pictures of common organisms. [Assessment Boundary: Assessment does not include molecular  objects/features they don't need - emphasis is on the matter explanations.]  these organisms need for survival. | environment.  need different things to grow and survive. | Identify which is an animal, plant, or decomposer using | Identify that animals must eat food (i.e., plants, other plants into matter that is food. Examples of systems could include  animals) and drink water to survive, and that plants need organisms, ecosystems, and the Earth.]   materials in soil, air and water to survive compared to common | Expand to include where in the environment such matter needed for survival comes from. Science Grade 5 |
| S05PHS1.1 | 5-PS1-1 | Oregon Science Standard 2022:  Oregon Alternate Academic Achievement Standard | Oregon Science Standard Clarifications/Assessment Boundary 2022:  Low (L), Medium (M), High (H) Parameters: [Clarification Statement: Examples of evidence could include  L: Identify the parts of large common and inanimate objects adding air to expand a basketball, compressing air in a syringe,  with easily recognizable smaller parts (e.g., cars/trucks - dissolving sugar in water, and evaporating salt water.]   wheels; buildings/houses - doors and windows; building blocks [Assessment Boundary: Assessment does not include the atomic- - smaller blocks). | small to be seen.  Recognize that objects, animals, and plants are made of smaller parts and identify various seen and unseen parts. |  | Identify the parts of a wider variety of inanimate objects unseen particles.]  (e.g., computer screen - keyboard) and common living organisms (e.g., dogs/cats/birds – arms/legs/eyes/wings; plants/trees – leaves/flowers/trunk). | Identify more complex parts of other common objects and living organisms including those that are too small to be seen (e.g., water/objects/animals/plants are made of atoms/molecules). Science Grade 5 |
| S05PHS1.2 | 5-PS1-2 | Oregon Science Standard 2022: Measure and graph quantities to  Oregon Alternate Academic Achievement Standard | Oregon Science Standard Clarifications/Assessment Boundary  L: Measure the weight/mass of common objects in various 2022:   phases of matter using pictures of such objects (e.g., an object Clarification Statement: Examples of reactions or changes could  on a scale that weighs 3 pounds). [Assessment Boundary: Assessment does not include  weighs less than a rock or glass of water) or choose the correct distinguishing mass and weight.]  tool to measure the weight/mass of objects. | when heating, cooling, or mixing substances, the total weight of  of different types of matter. matter is conserved. Low (L), Medium (M), High (H) Parameters: |  | Compare the weight/mass of common objects in various substances.]   stages of matter using pictures of such objects (e.g., a balloon | Compare the weight/mass of common objects in various phases of matter using graphs and data. Science Grade 5 |
| S05PHS1.3 | 5-PS1-3 | Oregon Science Standard 2022: Make observations and  Oregon Alternate Academic Achievement Standard | Oregon Science Standard Clarifications/Assessment Boundary 2022:   Low (L), Medium (M), High (H) Parameters: [Clarification Statement: Examples of materials to be identified  L: Properties include size and shape of common objects. [Assessment Boundary: Assessment does not include density or distinguishing mass and weight.] Science Grade 5 | properties of matter. |  | Properties include size, shape and extend to include and liquids. Examples of properties could include color, hardness,  hardness/softness and mass of objects. | Properties include size, shape, hardness/softness, mass, and to magnetic forces, and solubility; density is not intended as an  volume, including the use of graphs and picture representations identifiable property.]   of matter in different phases (i.e., solid, liquid, vapor/gas). |
| S05PHS1.4 | 5-PS1-4 | Oregon Science Standard 2022: Conduct an investigation to  Oregon Alternate Academic Achievement Standard | Oregon Science Standard Clarifications/Assessment Boundary  Low (L), Medium (M), High (H) Parameters: [Clarification Statement: Emphasis is to investigate the effect of  substance (e.g., rocks and soil, objects in sand). [Assessment Boundary: Assessment does not include having  gasses that when mixed form a new substance (e.g., salt water, students distinguish between mass and weight. This specific  fruit punch, paint, air). distinction occurs in middle grades.] Science Grade 5 | new substances.  mixed together. | Recognize two solids mixed together that do not form a new | Recognize one solid and one liquid mixed together that do formed. Quantitative or qualitative data will be collected (e.g.  not form a new substance (e.g., sand and water). | Picture of one solid and one liquid, two liquids or two |
| S05PHS2.1 | 5-PS2-1 | Oregon Science Standard 2022: Support an argument that the  Oregon Alternate Academic Achievement Standard | Oregon Science Standard Clarifications/Assessment Boundary  Low (L), Medium (M), High (H) Parameters: [Clarification Statement: “Down” is a local description of the  direction common objects will fall when dropped (i.e., a ball direction that points toward the center of the spherical Earth.]   moves downward when dropped). [Assessment Boundary: Assessment does not include  M: Incorporate the concept of gravity into questions (i.e., mathematical representation of gravitational force.]  similar questions as L-level, but specifically using the word "gravity"). | objects fall downward. | Restrict questions/pictures/diagrams to asking about the |  | Incorporate more abstract diagrams (i.e., of larger land areas/the Earth/Moon in space) with and without objects in diagrams that ask about the influence of gravity. Science Grade 5 |
| S05PHS3.1 | 5-PS3-1 | Oregon Science Standard 2022: Use models to describe that  Oregon Alternate Academic Achievement Standard | Oregon Science Standard Clarifications/Assessment Boundary  Low (L), Medium (M), High (H) Parameters: [Clarification Statement: Examples of models could include  space objects) gives the vast majority of light and heat energy diagrams, and flow charts.]  to the Earth. [Assessment Boundary: Assessment does not include  M: Identify that the Sun gives light and heat energy to photosynthesis or the photosynthesis reaction equation. Students  organisms (e.g., plants and animals) on Earth for survival. | to maintain body warmth) was once energy from the Sun.    Earth and living organisms with energy. | Identify that the Sun (compared to other space and/or non- |  | Recognize that the Sun gives light and heat energy to plants they do not need to know the specifics of the process or equation.  and animals on Earth, which in turn provide humans with Similarly, this assessment does not include the process or  energy (i.e., for survival, body repair, growth and motion). mechanisms for metabolism. Students should understand the relationship between animals and the food they eat to obtain energy for bodily functions, growth, and repair.] Standards not Essentialized: Please refer to Oregon’s published content standards for the full description and context of these codes. 3-5-ETS1-3 |


## Science Grade 8

| ORExt Standard Code | Equivalent ODE Standard | Oregon Science Standard 2022 | Clarifications / Assessment Boundary 2022 | Essentialized Standard | Low (L) | Medium (M) | High (H) |
|---|---|---|---|---|---|---|---|
| S08ESS1.2 | MS-ESS1-2 and MS-PS2-4 | Oregon Science Standard 2022:   Oregon Alternate Academic Achievement Standard | MS-ESS1-2: [Clarification Statement: Emphasis for the model is  the use of the term. [Assessment Boundary: Assessment does not include Kepler’s Laws of orbital motion or the apparent retrograde motion of the planets as viewed from Earth.] MS-PS2-4: [Clarification Statement: Examples of evidence for arguments could include data generated from simulations or digital tools; and charts displaying mass, strength of interaction, distance from the Sun, and orbital periods of objects within the solar system.] [Assessment Boundary: Assessment does not include Newton’s Law of Gravitation or Kepler’s Laws.] Science Grade 8 | gravity in the motions within galaxies and the solar system.  way objects move on Earth and in space (progression from MS-PS2-4: Construct and present arguments using evidence to  S05PHS2.1). support the claim that gravitational interactions are attractive and depend on the masses of interacting objects.    Low (L), Medium (M), High (H) Parameters: | Use questions and diagrams to ask about the direction that Oregon Science Standard Clarifications/Assessment  common objects will fall when dropped (i.e., a ball moves Boundary 2022:   downward when dropped) based on the role of gravity, including | Extend L-level to include role of gravity involving Earth- Milky Way galaxy and controls orbital motions within them.  Moon relations and Earth-Sun relations. | Extend M-level  to include role of gravity involving other distance along a football field or computer visualizations of  objects in the solar system (e.g., other planets and the Sun, elliptical orbits) or conceptual (such as mathematical proportions  moons of other planets, comets). relative to the size of familiar objects such as students’ school or state).] |
| S08ESS1.3 | MS-ESS1-3 | Oregon Science Standard 2022: Analyze and interpret data to  Oregon Alternate Academic Achievement Standard | [Clarification Statement: Emphasis is on the analysis of data from  L: Identify the Sun and the Earth as compared to other unrelated Earth-based instruments, space-based telescopes, and spacecraft  objects here on Earth. [Assessment Boundary: Assessment does not include recalling  and models. facts about properties of the planets and other solar system bodies.] Science Grade 8 | solar system and their features. Oregon Science Standard Clarifications/Assessment Boundary 2022:   Low (L), Medium (M), High (H) Parameters: |  | Identify the Sun, Earth, and Moon as compared to other objects. Examples of scale properties include the sizes of an  related space objects in the solar system. | Extend M-level to involve the comparison of various objects (such as volcanoes), and orbital radius. Examples of data include  (e.g., their size or shape) in the solar system (i.e., Sun, Moon, statistical information, drawings and photographs, and models.]   Earth, other planets, comets, asteroids) using diagrams, graphs, |
| S08ESS2.2 | MS-ESS2-2 | Oregon Science Standard 2022: Construct an explanation based  Oregon Alternate Academic Achievement Standard | [Clarification Statement: Emphasis is on how processes change  model (e.g., water, ice, or wind). | surface at varying time and spatial scales.  processes that shape the Earth (progression from S05ESS2.1). Oregon Science Standard Clarifications/Assessment  Low (L), Medium (M), High (H) Parameters: | Identify the process that leads to erosion when provided a | Identify conditions that lead to specific types of surface as slow plate motions or the uplift of large mountain ranges) or  weathering (i.e., with water, ice, or wind as mechanism). | Identify geoscience processes that shape local geographic reactions), and how many geoscience processes (such as  features (e.g., earthquakes, volcanoes, river erosion, earthquakes, volcanoes, and meteor impacts) usually behave  meteorites/craters). gradually but are punctuated by catastrophic events. Examples of geoscience processes include surface weathering and deposition by the movements of water, ice, and wind. Emphasis is on geoscience processes that shape local geographic features, where appropriate.] Science Grade 8 |
| S08ESS2.4 | MS-ESS2-4 | Oregon Science Standard 2022: Develop a model to describe  Oregon Alternate Academic Achievement Standard | Clarification Statement: Emphasis is on the ways water changes  unrelated objects. [Assessment Boundary: A quantitative understanding of the  water cycle using diagrams and picture representations. latent heats of vaporization and fusion is not assessed.] Science Grade 8 | from the Sun and the force of gravity.    and how water changes, including through the water cycle. Oregon Science Standard Clarifications/Assessment  Low (L), Medium (M), High (H) Parameters: | Identify the three forms of water as compared to other | Identify a specific form of water as compared to other forms hydrologic cycle. Examples of models can be conceptual or  of water. | Connect the forms of water to various (simple) points in the |
| S08ESS2.5 | MS-ESS2-5 | Oregon Science Standard 2022: Collect data to provide  Oregon Alternate Academic Achievement Standard | [Clarification Statement: Emphasis is on how air masses flow  cloudy, sunny, foggy, stormy, etc.) as compared to objects or from regions of high pressure to low pressure, causing weather  conditions that are unrelated. [Assessment Boundary: Assessment does not include recalling the names of cloud types or weather symbols used on weather maps or the reported diagrams from weather stations.] Science Grade 8 | masses result in changes in weather conditions.  conditions and their characteristics. Oregon Science Standard Clarifications/Assessment  Low (L), Medium (M), High (H) Parameters: | Identify different simple weather conditions (i.e., rain, | Identify different simple weather conditions (i.e., rain, wind) at a fixed location to change over time, and how sudden  cloudy, sunny, foggy, etc.) as compared to objects or conditions changes in weather can result when different air masses collide.  that are related (i.e., other weather conditions). | Connect physical conditions to weather (e.g., wet to rain, dry ranges. Examples of data can be provided to students (such as  or hot to sunny). weather maps, diagrams, and visualizations) or obtained through laboratory experiments (such as with condensation).] |
| S08ESS3.3 | MS-ESS3-3 | Oregon Science Standard 2022: Apply scientific principles to  Oregon Alternate Academic Achievement Standard | [Clarification Statement: Examples of the design process include  L: Identify which among several simple and common choices is a examining human environmental impacts, assessing the kinds of  way to protect or help the Earth/environment (e.g., putting trash solutions that are feasible, and designing and evaluating solutions  in can, recycling, riding bike for transportation, using less water) that could reduce that impact. Examples of human impacts can  as compared to common and unrelated activities (e.g., playing include water usage (such as the withdrawal of water from  with a toy, reading a book). | on the environment.*  communities protect the Earth's environment (progression from S05ESS3.1). Oregon Science Standard Clarifications/Assessment Boundary 2022:   Low (L), Medium (M), High (H) Parameters: |  | Identify which of several simple and common choices is a usage (such as urban development, agriculture, or the removal of  way to protect or help the Earth/environment (e.g., putting trash wetlands), and pollution (such as of the air, water, or land).]  in can, recycling, riding bike) as compared to activities that pollute or harm the Earth (e.g., pollution from a factory, littering in streams/ocean, oil spilling from a ship). | Identify and compare simple methods for monitoring or reducing human impact on the Earth/environment (e.g., a graph comparing the amount of trash three cities produce, the amount of water three cities consume, the amount of materials recycled by three schools). * This performance expectation integrates traditional science content with engineering through a practice or disciplinary core idea. Science Grade 8 |
| S08ESS3.4 | MS-ESS3-4 | Oregon Science Standard 2022: Construct an argument  Oregon Alternate Academic Achievement Standard | [Clarification Statement: Examples of evidence include grade- or objects. | and per-capita consumption of natural resources impact Earth’s  communities use and impact the Earth's resources (progression systems.  from S05ESS3.1). Oregon Science Standard Clarifications/Assessment  Low (L), Medium (M), High (H) Parameters: | Identify natural resources as compared to other unrelated items | Identify natural resources based on their use (e.g., Which is consumption of food and natural resources (such as freshwater,  burned for fire?; Which do we use for energy?). | Extend M-level to human use of natural resources and its to the appearance, composition, and structure of Earth’s systems  effects using simple graphs and diagrams (e.g., Which city as well as the rates at which they change. The consequences of  consumes/produces the most food resources/water/energy?). increases in human populations and consumption of natural resources are described by science, but science does not make the decisions for the actions society takes.] Science Grade 8 |
| S08ETS1.1 | MS-ETS1-1 | Oregon Science Standard 2022: Define the criteria and  Oregon Alternate Academic Achievement Standard |  | a successful solution, taking into account relevant scientific  problems, including design-related problems, that impact people principles and potential impacts on people and the natural  and the environment (progression from S05ETS1.1). environment that may limit possible solutions. Low (L), Medium (M), High (H) Parameters: | Questions are of the type “Which shows a (design) problem to solve?”, and are restricted to a picture and description of a simple problem compared to other activities or situations that are obviously not (e.g., flat tire/missing bike tire/broken toy compared to reading a book, eating food, driving a car). | Questions are of the type “Which shows a (design) problem to solve?”, and are restricted to more complex problems (e.g., displaying cars/airplanes) with answers showing a possible (design) problem compared to those that are not (e.g., running out of fuel, missing a wheel/wing vs. car driving/plane flying). | Extend the complexity of M-level, including the use of graphs (e.g., weakest material among distractors) and diagrams, and questions about likelihood based on simple data (e.g., Which material is likely to break first?). Science Grade 8 |
| S08ETS1.2 | MS-ETS1-2 | Oregon Science Standard 2022: Evaluate competing design  Oregon Alternate Academic Achievement Standard |  | meet the criteria and constraints of the problem.  solutions to different problems, including design-related problems, that impact people and the environment (progression from S05ETS1.2). Low (L), Medium (M), High (H) Parameters: | Questions involve simple solutions and are restricted to common problems and solutions and/or the tools that solve them (i.e., flat bike/car tire - use a bike pump: plants dying – use a sprinkler or hose/give plant food: nail or screw sticking out - use a hammer or screwdriver) compared to obvious non- solutions/unrelated actions (e.g., play outside, go to the park). | Questions involve simple solutions and are restricted to common problems and actions and/or the tools that solve them (i.e., flat bike/car tire - use a pump: plants in garden dying – use sprinkler or hose/give plant food: nail or a screw sticking out - use a hammer or screwdriver) compared to solutions to other similar problems. | Extend the complexity of M-level, including the use of graphs (e.g., strongest metal, hardest material, best material for making something) and diagrams (e.g., simple flow charts). Science Grade 8 |
| S08LFS1.3 | MS-LS1-3 | Oregon Science Standard 2022: Construct an explanation  Oregon Alternate Academic Achievement Standard | [Clarification Statement: Emphasis should be on the function and  M: Identify simple internal parts or systems of the body using interactions of the major body systems (e.g. circulatory,  simple terminology and diagrams. [Assessment Boundary: Assessment is focused on the interactions  (e.g., skeletal system/bones providing structure, muscles between systems not on the functions of individual systems.]  providing strength for movement). Science Grade 8 | interacting systems consisting of cells, tissues, and organs  the human body, including that they are composed of different working together to maintain homeostasis.  materials and have different functions. Oregon Science Standard Clarifications/Assessment  Low (L), Medium (M), High (H) Parameters: | Identify simple external parts of the body. |  | Connect human body parts to their materials and function |
| S08LFS1.4 | MS-LS1-4 | Oregon Science Standard 2022: Use argument based on  Oregon Alternate Academic Achievement Standard | Oregon Science Standard Clarifications/Assessment Boundary  Low (L), Medium (M), High (H) Parameters: [Clarification Statement: Emphasis is on both animals and plants  (e.g., Which is an animal?). | explanation for how characteristic animal behaviors and  animals and plants better survive (i.e., behaviors/structures in specialized plant structures affect the probability of successful  animals and structures in plants connected to successful reproduction of animals and plants respectively.  functions) (progression from S05LFS1.1, S05LFS1.2). | Identify or distinguish animals and plants from other objects | Identify different animal and plant behaviors and structures probability of animal reproduction could include nest building to  (e.g., Which part is the flower? Which part shows the ears?; protect young from cold, herding of animals to protect young from  Which shows a bear hibernating?). | Connect animal and plant behaviors/structures to their attract mates for breeding. Examples of animal behaviors that  function (e.g., Which body parts help the cheetah run fast?; affect the probability of plant reproduction could include  Which tree gets the most sunlight?; Which body parts help the transferring pollen or seeds and creating conditions for seed  owl see prey at night?). germination and growth. Examples of plant structures could include bright flowers attracting butterflies that transfer pollen, flower nectar and odors that attract insects that transfer pollen, and hard shells on nuts that squirrels bury.] Science Grade 8 |
| S08LFS1.6 | MS-LS1-6 | Oregon Science Standard 2022: Construct a scientific  Oregon Alternate Academic Achievement Standard | Oregon Science Standard Clarifications/Assessment Boundary 2022:   Low (L), Medium (M), High (H) Parameters: [Clarification Statement: Emphasis is on tracing movement of  L: Questions use simple pictures and diagrams to ask what a matter and flow of energy.]   plant/tree/flower needs to grow (i.e., the correct answer being [Assessment Boundary: Assessment does not include the  light, water, or air compared to materials that would not help it biochemical mechanisms of photosynthesis.]  grow such as complete darkness, soda, salt). | cycling of matter and flow of energy into and out of organisms.  and water to grow through a process called photosynthesis (progression from S05LFS1.1). |  | Questions use simple pictures and diagrams to compare the (potential) growth of a plant/tree/flower (if one is given light, water, and/or air, and the other is not), while including the term/role/description of photosynthesis in questions about what would help the plant grow (comparisons between two different plants may be used). | Extend M-level by incorporating into diagrams images of the Sun, arrows that indicate flow of energy, intake of carbon dioxide, release of oxygen, with questions pertaining to growth under different environmental conditions during photosynthesis. Science Grade 8 |
| S08LFS1.7 | MS-LS1-7 | Oregon Science Standard 2022: Develop a model to describe  Oregon Alternate Academic Achievement Standard | Oregon Science Standard Clarifications/Assessment Boundary  Low (L), Medium (M), High (H) Parameters: [Clarification Statement: Emphasis is on describing that molecules  grow (e.g., Which do you eat to grow?; Which helps the kitten are broken apart and put back together and that in this process,  grow?). [Assessment Boundary: Assessment does not include details of the  to humans and animals. | molecules that support growth and/or release energy as this matter  organisms grow and obtain energy (progression from moves through an organism.  S05LFS2.1). | Questions are related to humans and animals needing food to | Extend L-level questions to involve food providing "energy" | Introduce graphical displays/diagrams to ask questions about the relative amount of energy or expected growth based on a given situation (e.g., a bar chart showing varying amounts of food/water given to a pet/plant). Science Grade 8 |
| S08LFS2.1 | MS-LS2-1, MS-LS1-5 and MS-LS2-4 | Oregon Science Standard 2022:   Oregon Alternate Academic Achievement Oregon Science Standard Clarifications/Assessment Boundary 2022:   Which is a living organism?; Which shows a group | MS-LS2-1: [Clarification Statement: Emphasis is on cause and effect  of living animals?). MS-LS1-5: [Clarification Statement: Examples of local environmental  H: Extend M-level to involve simple changes in conditions could include availability of food, light, space, and water. Examples  resources and how such changes might affect an of genetic factors could include large breed cattle and species of grass affecting  individual or group of living organisms. growth of organisms. Examples of evidence could include drought decreasing plant growth, fertilizer increasing plant growth, different varieties of plant seeds growing at different rates in different conditions, and fish growing larger in large ponds than they do in small ponds.] [Assessment Boundary: Assessment does not include genetic mechanisms, gene regulation, or biochemical processes.] MS-LS2-4: [Clarification Statement: Emphasis is on recognizing patterns in data and making warranted inferences about changes in populations, and on evaluating empirical evidence supporting arguments about changes to ecosystems.] Science Grade 8 | resource availability on organisms and populations of organisms in an  that the availability of and changes in resources ecosystem.  (i.e., food, water, shelter, habitat) effects the growth MS-LS1-5: Construct a scientific explanation based on evidence for how  and number of living organisms in an ecosystem environmental and genetic factors influence the growth of organisms.  (progression from S05LFS2.1). MS-LS2-4: Construct an argument supported by empirical evidence that changes to physical or biological components of an ecosystem affect  Low (L), Medium (M), High (H) Parameters: | Differentiate between individual living organisms and groups of living organisms (e.g., | Identify various resources that individual or numbers of organisms in ecosystems during periods of abundant and scarce  groups of living organisms need to grow, resources.]  reproduce, or sustain their population. |  |
| S08LFS2.2 | MS-LS2-2 | Oregon Science Standard 2022: Construct an explanation that  Oregon Alternate Academic Achievement Standard | Oregon Science Standard Clarifications/Assessment Boundary 2022:   Low (L), Medium (M), High (H) Parameters: [Clarification Statement: Emphasis is on predicting consistent  L: Identify related living organisms versus (specifically) non- patterns of interactions in different ecosystems in terms of the  living parts of ecosystems and vice versa (e.g., Which shows a relationships among and between organisms and abiotic  pond - pond, frog, fish). | ecosystems.  organisms interact with other living and non-living ecosystem components. |  | Extend L-level to involve interactions between living and could include competitive, predatory, and mutually beneficial.]  non-living aspects of a given ecosystem (e.g., habitat, shelter, water). | Extend M-level to involve interaction between individual or groups of living organisms (e.g., predator-prey, competitive, mutually beneficial). Science Grade 8 |
| S08LFS3.2 | MS-LS3-2 | Oregon Science Standard 2022: Develop and use models to  Oregon Alternate Academic Achievement Standard | Oregon Science Standard Clarifications/Assessment Boundary  L: Identify (match) the offspring of a given living organism (i.e., 2022:   plants, animals, humans): answer should be exactly or very [Clarification Statement: Emphasis is on using models such as  closely identical and distractors include different species. | identical genetic information and sexual reproduction results in  produces offspring with similar though varied traits. offspring with genetic variation. Low (L), Medium (M), High (H) Parameters: |  | Identify the offspring of a given living organism (i.e., plants, and effect relationship of gene transmission from parent(s) to  animals, humans): answer should not be identical, and offspring and resulting genetic variation.]  distractors should be different species. | Identify the offspring of a given living organism (i.e., plants, animals, humans): should not be identical, and include variations of the same and different species. Science Grade 8 |
| S08LFS4.2 | MS-LS4-2 and MS-LS4-1 | Oregon Science Standard 2022:   Oregon Alternate Academic Achievement Standard | Oregon Science Standard Clarifications/Assessment Boundary  M: Identify similar animals based on their physical 2022:   characteristics with more reasonable distractors (e.g., lion with MS-LS4-2: [Clarification Statement: Emphasis is on explanations  cat). MS-LS4-1: [Clarification Statement: Emphasis is on finding patterns of changes in the level of complexity of anatomical structures in organisms and the chronological order of fossil appearance in the rock layers.] [Assessment Boundary: Assessment does not include the names of individual species or geological eras in the fossil record.] Science Grade 8 | the anatomical similarities and differences among modern  organisms, including that they are likely related. organisms and between modern and fossil organisms to infer evolutionary relationships.  Low (L), Medium (M), High (H) Parameters: | Identify like animals based on their physical characteristics record that document the existence, diversity, extinction, and  (i.e., dogs with dogs, or cats with cats, with distractors being change of life forms throughout the history of life on Earth under  very different organisms such as a bug and bird, while like the assumption that natural laws operate today as in the past.  animals look slightly different - e.g., add spots, face a different way). |  | Extend M-level to include fossils of common extinct similarity or differences of the gross appearance of anatomical  organisms. structures.] |
| S08LFS4.4 | MS-LS4-4 | Oregon Science Standard 2022: Construct an explanation based  Oregon Alternate Academic Achievement Standard | Oregon Science Standard Clarifications/Assessment Boundary  L: Identify simple traits of animals that help them survive or 2022:   reproduce (though not referring to survival/reproduction) as [Clarification Statement: Emphasis is on using simple probability  compared to traits or objects that are unrelated to animal. | population increase some individuals’ probability of surviving and  organisms survive. reproducing in a specific environment. Low (L), Medium (M), High (H) Parameters: |  | Extend L-level by directly referring to/asking about traits that help them survive as compared to traits from other animals that help them survive. | Questions ask about the function of traits related to a single animal or group of same animal (e.g., Which trait helps the giraffe reach food from the tops of trees?; Which trait helps the owl see prey in the dark?) among other traits of the target animal. Science Grade 8 |
| S08PHS1.2 | MS-PS1-2 | Oregon Science Standard 2022: Analyze and interpret data on  Oregon Alternate Academic Achievement Standard | Oregon Science Standard Clarifications/Assessment Boundary 2022:   Low (L), Medium (M), High (H) Parameters: [Clarification Statement:    L: Identify and compare simple physical properties including Examples of reactions could include burning sugar or steel wool,  size, shape, hardness/softness, weight, mass and density of fat reacting with sodium hydroxide, and mixing zinc with  common objects, with the chemical property restricted to hydrogen chloride.]   whether or not a substance is flammable. [Assessment Boundary: Assessment is limited to analysis of the  M: Properties include all of those in L-level and may involve following properties: density, melting point, boiling point,  identifying properties after a physical/chemical change to a solubility, flammability, and odor.]  given substance, including the use of graphs and data tables of such properties. | interact to determine if a chemical reaction has occurred.  and chemical properties of matter, including before or after they change (progression from 5.PHS1.3). |  |  | Extend M-level to physical versus chemical changes, including which has occurred and simple results. Science Grade 8 |
| S08PHS1.3 | MS-PS1-3 | Oregon Science Standard 2022: Gather and make sense of  Oregon Alternate Academic Achievement Standard | Oregon Science Standard Clarifications/Assessment Boundary  Low (L), Medium (M), High (H) Parameters: [Clarification Statement: Emphasis is on natural resources that  materials. [Assessment Boundary: Assessment is limited to qualitative  everyday objects or materials come from (e.g., paper comes information.]  from wood/trees, metal in a car comes from iron/aluminum). Science Grade 8 | resources and impact society.  and that they come from the Earth's natural resources. | Identify different types of common and everyday objects or | Identify different types of common and everyday objects or Examples of new materials could include new medicine, foods,  materials that come from natural resources. | Identify the natural resource from which common and |
| S08PHS2.1 | MS-PS2-1 | Oregon Science Standard 2022: Apply Newton’s Third Law to  Oregon Alternate Academic Achievement Standard | Oregon Science Standard Clarifications/Assessment Boundary  Low (L), Medium (M), High (H) Parameters: [Clarification Statement: Examples of practical problems could  M: Identify actions that will involve an associated reaction. [Assessment Boundary: Assessment is limited to vertical or horizontal interactions in one dimension.] *This performance expectation integrates traditional science content with engineering through a practice or disciplinary core idea. Science Grade 8 | colliding objects.*   actions, including associated reactions. | Identify objects that are at rest or in motion. |  | Identify and associate simple actions and reactions. and stationary objects, and between a meteor and a space vehicle.] |
| S08PHS2.2 | MS-PS2-2 | Oregon Science Standard 2022: Plan an investigation to provide  Oregon Alternate Academic Achievement Standard | Oregon Science Standard Clarifications/Assessment Boundary  Low (L), Medium (M), High (H) Parameters: [Clarification Statement: Emphasis is on balanced (Newton’s First  M: Qualitatively link mass with force and motion. [Assessment Boundary: Assessment is limited to forces and changes in motion in one-dimension in an inertial reference frame and to change in one variable at a time. Assessment does not include the use of trigonometry.] Science Grade 8 | of the forces on the object and the mass of the object.    motion of objects are related and comparable. | Identify or compare objects in relation to their mass. |  | Qualitatively compare forces, mass, and changes in motion in of forces, mass and changes in motion (Newton’s Second Law),  various situations. frame of reference, and specification of units.] |
| S08PHS3.4 | MS-PS3-4, MS-PS1-4, and MS-PS3-3 | Oregon Science Standard 2022:   Oregon Alternate Academic Achievement Oregon Science Standard Clarifications/Assessment Boundary 2022:   cold (e.g., using objects, outside vs. inside). | MS-PS3-4: [Clarification Statement: Examples of experiments could include  M: Recognize that hot and cold are related to comparing final water temperatures after different masses of ice melted in the same  measures of temperature, including changes volume of water with the same initial temperature, the temperature change of  in temperature. energy is added.] [Assessment Boundary: Assessment does not include calculating  maximized (e.g., wearing a coat to stay the total amount of thermal energy transferred.]  warm). MS-PS1-4: [Clarification Statement: Emphasis is on qualitative molecular-level models of solids, liquids, and gases to show that adding or removing thermal energy increases or decreases kinetic energy of the particles until a change of state occurs. Examples of models could include drawings and diagrams. Examples of particles could include molecules or inert atoms. Examples of pure substances could include water, carbon dioxide, and helium.] MS-PS3-3: [Clarification Statement: Examples of devices could include an insulated box, a solar cooker, and a Styrofoam cup.] [Assessment Boundary: Assessment does not include calculating the total amount of thermal energy transferred.] Science Grade 8 | transferred, the type of matter, the mass, and the change in the average kinetic energy  Recognize temperature as a measure of how of the particles as measured by the temperature of the sample.  hot or cold matter is, and that heat is MS-PS1-4: Develop a model that predicts and describes changes in particle motion,  transferable. temperature, and state of a pure substance when thermal energy is added or removed. MS-PS3-3: Apply scientific principles to design, construct, and test a device that  Low (L), Medium (M), High (H) either minimizes or maximizes thermal energy transfer.  Parameters: | Recognize the difference between hot and |  | Identify examples of heat transfer, and environment, or the same material with different masses when a specific amount of  how such transfer might be minimized or |
| S08PHS4.2 | MS-PS4-2 and MS-PS4-1 | Oregon Science Standard 2022:   Oregon Alternate Academic Achievement Standard | Oregon Science Standard Clarifications/Assessment Boundary  M: Describe waves qualitatively. MS-PS4-2: [Clarification Statement: Emphasis is on both light and mechanical waves. Examples of models could include drawings, simulations, and written descriptions.] [Assessment Boundary: Assessment is limited to qualitative applications pertaining to light and mechanical waves.] MS-PS4-1: [Clarification Statement: Emphasis is on describing waves with both qualitative and quantitative thinking.] [Assessment Boundary: Assessment does not include electromagnetic waves and is limited to standard repeating waves.] Standards not Essentialized: Please refer to Oregon’s published content standards for the full description and context of these codes. MS-ESS1-1  MS-ESS3-5  MS-LS2-5  MS-PS1-6 MS-ESS1-4  MS-ETS1-3  MS-LS3-1  MS-PS2-3 MS-ESS2-1  MS-ETS1-4  MS-LS4-3  MS-PS2-5 MS-ESS2-3  MS-LS1-1  MS-LS4-5  MS-PS3-1 MS-ESS2-6  MS-LS1-2  MS-LS4-6  MS-PS3-2 MS-ESS3-1  MS-LS1-8  MS-PS1-1  MS-PS3-5 MS-ESS3-2  MS-LS2-3  MS-PS1-5  MS-PS4-3 | reflected, absorbed, or transmitted through various materials.  mechanical (e.g., ocean sound) and electromagnetic (e.g., light) MS-PS4-1: Use mathematical representations to describe a simple  waves, and describe/compare them qualitatively/quantitatively. model for waves that includes how the amplitude of a wave is related to the energy in a wave.  Low (L), Medium (M), High (H) Parameters: | Identify waves as compared to other objects. |  | Describe or compare waves qualitatively and quantitatively. |


## Science High School

| ORExt Standard Code | Equivalent ODE Standard | Oregon Science Standard 2022 | Clarifications / Assessment Boundary 2022 | Essentialized Standard | Low (L) | Medium (M) | High (H) |
|---|---|---|---|---|---|---|---|
| S11ESS1.1 | HS-ESS1-1 | Oregon Science Standard 2022: Develop a model based on  Oregon Alternate Academic Achievement Standard | Oregon Science Standard Clarifications/Assessment Boundary 2022:   Low (L), Medium (M), High (H) Parameters: [Clarification Statement: Emphasis is on the energy transfer  L: Recognize that the Sun (compared to other space and non- mechanisms that allow energy from nuclear fusion in the Sun’s  space objects) gives light and heat energy to the Earth. [Assessment Boundary: Assessment does not include details of the  radiation. H-level specifically uses the term "radiation" and can atomic and sub-atomic processes involved with the Sun’s nuclear  introduce types of radiation beyond heat and visible light (e.g., fusion.]  infra-red, ultraviolet, x-ray), though questions/diagrams/graphs should remain clear and simplistic (e.g., Which is a type of radiation the Sun sends to the Earth? - ultraviolet, rain, wind). Science High School | nuclear fusion in the Sun’s core to release energy that eventually  Earth and living organisms with different types of energy, reaches Earth in the form of radiation.  including in the form of radiation (progression from S05PHS3.1). |  | Recognize that the Sun gives light and heat energy to the observations of the masses and lifetimes of other stars, as well as  Earth and its organisms (e.g., plants and animals) compared to the ways that the Sun’s radiation varies due to sudden solar flares  other space and non-space objects. | Recognize that the Sun gives energy to the Earth, plants and variations over centuries.]   animals, and thus, humans in the form of different types of |
| S11ESS1.4 | HS-ESS1-4 | Oregon Science Standard 2022: Use mathematical or  Oregon Alternate Academic Achievement Standard | [Clarification Statement: Emphasis is on Newtonian gravitational  Low (L), Medium (M), High (H) Parameters: [Assessment Boundary: Mathematical representations for the  gravity/orbiting motion to the Moon around the Earth and the gravitational attraction of bodies and Kepler’s Laws of orbital  Earth around the Sun. | objects in the solar system.  natural and manmade objects in the solar system, including how they orbit due to gravity (progression from S08ESS1.2, Oregon Science Standard Clarifications/Assessment  S08ESS1.3). Boundary 2022: | Identify the Sun, Earth, and Moon as compared to other satellites as well as planets and moons.]   objects in the solar system; restrict questions related to | Extend to identify or ask questions about the features of or calculus.]  the role of gravity in the orbit of other natural objects in the solar system (i.e., Sun, Moon, Earth, other planets). | Extend M-level to include questions about identifying or the features of additional natural and manmade objects and their orbit around the Earth, the Sun, or other planets (or other moons, comets, asteroids and man-made satellites) including through the use of diagrams and/or graphs. Science High School |
| S11ESS2.1 | HS-ESS2-1 | Oregon Science Standard 2022: Develop a model to illustrate  Oregon Alternate Academic Achievement Standard | [Clarification Statement: Emphasis is on how the appearance of  weathering (i.e., with water, ice, or wind as vehicle - Which land features (such as mountains, valleys, and plateaus) and sea- shows water erosion?). [Assessment Boundary: Assessment does not include  (e.g., Which type of erosion process likely led to the canyon?; memorization of the details of the formation of specific  Which feature is associated with recent volcanism?). geographic features of Earth’s surface.] Science High School | spatial and temporal scales to form continental and ocean-floor  processes that shape the Earth including associated Earth features.  features (progression from S08ESS2.2). Oregon Science Standard Clarifications/Assessment  Low (L), Medium (M), High (H) Parameters: | Identify conditions that lead to specific types of surface | Identify geoscience processes that shape local geographic result of both constructive forces (such as volcanism, tectonic  features (e.g., earthquakes, rivers, volcanoes, meteorites/craters - uplift, and orogeny) and destructive mechanisms (such as  Which is an example of volcanism?). | Extend M-level by linking features to the geoscience process |
| S11ESS2.5 | HS-ESS2-5 | Oregon Science Standard 2022: Plan and conduct an  Oregon Alternate Academic Achievement Standard | [Clarification Statement: Emphasis is on mechanical and  L: Identify the three forms of water as compared to other related chemical investigations with water and a variety of solid  substances (i.e., near distractor might be another form of water, materials to provide the evidence for connections between the  far could be another chemical or other natural object/substance). | materials and surface processes.  forms of water and how water changes, including through various stages of the water cycle (progression from S08ESS2.4). Oregon Science Standard Clarifications/Assessment Boundary 2022:   Low (L), Medium (M), High (H) Parameters: |  | Identify and ask questions about the three forms of water as rock cycle. Examples of mechanical investigations include stream  compared to other forms of water. | Extend M-level to connect the forms of water to various variations in soil moisture content, or frost wedging by the  points in the water cycle using diagrams and picture models, expansion of water as it freezes. Examples of chemical  including specific questions about the three forms using graphic investigations include chemical weathering and recrystallization  representations. (by testing the solubility of different materials) or melt generation (by examining how water lowers the melting temperature of most solids).] Science High School |
| S11ESS3.1 | HS-ESS3-1, HS-ESS3-3, and HS-ESS3-5 | Oregon Science Standard 2022:   Oregon Alternate Academic Achievement Standard | Oregon Science Standard Clarifications/Assessment Boundary  processes (e.g., Which shows a hurricane?; Which shows rain?). HS-ESS3-1: [Clarification Statement: Examples of key natural  and aspects of weather/climate to their impact on humans (e.g., resources include access to fresh water (such as rivers, lakes, and  Which is burned for fire?; Which do we use for energy?; Which groundwater), regions of fertile soils such as river deltas, and high  is a natural disaster that is dangerous to humans?; Which of the concentrations of minerals and fossil fuels. Examples of natural  following involves a change in weather or climate?). hazards can be from interior processes (such as volcanic eruptions and earthquakes), surface processes (such as tsunamis, mass wasting, and soil erosion), and severe weather (such as hurricanes, floods, and droughts). Examples of the results of changes in climate that can affect populations or drive mass migrations include changes to sea level, regional patterns of temperature and precipitation, and the types of crops and livestock that can be raised.] Science High School HS-ESS3-3: [Clarification Statement: Examples of factors that affect the management of natural resources include costs of resource extraction and waste management, per-capita consumption, and the development of new technologies. Examples of factors that affect human sustainability include agricultural efficiency, levels of conservation, and urban planning.] [Assessment Boundary: Assessment for computational simulations is limited to using provided multi-parameter programs or constructing simplified spreadsheet calculations.] HS-ESS3-5: [Clarification Statement: Examples of evidence, for both data and climate model outputs, are for climate changes (such as precipitation and temperature) and their associated impacts (such as on sea level, glacial ice volumes, or atmosphere and ocean composition).] [Assessment Boundary: Assessment is limited to one example of a climate change and its associated impacts.] Science High School | the availability of natural resources, occurrence of natural hazards,  other living organisms are influenced by natural resources, and changes in climate have influenced human activity.  natural hazards, and weather or climate changes (progression HS-ESS3-3: Create a computational simulation to illustrate the  from S08ESS2.5). relationships among management of natural resources, the sustainability of human populations, and biodiversity.  Low (L), Medium (M), High (H) Parameters: | Identify natural resources, natural hazards and aspects of climate models to make an evidence-based forecast of the current  weather/climate as compared to other unrelated items or rate of global or regional climate change and associated future  objects. | Identify natural resources, natural hazards and aspects of weather/climate as compared to other related materials | Extend M-level by linking resource use and natural hazards |
| S11ESS3.4 | HS-ESS3-4, HS-LS2-7, and HS-LS4-6 | Oregon Science Standard 2022:   Oregon Alternate Academic Achievement Oregon Science Standard Clarifications/Assessment Boundary 2022:   way to protect or help the Earth (e.g., putting trash in | HS-ESS3-4: [Clarification Statement: Examples of data on the impacts of  can, recycling, riding bike) as compared to activities human activities could include the quantities and types of pollutants  that pollute or harm the Earth (e.g., pollution from a released, changes to biomass and species diversity, or areal changes in land  factory, littering in streams/ocean, oil spilling from a surface use (such as for urban development, agriculture and livestock, or  ship). HS-LS2-7: [Clarification Statement: Examples of human activities can  cities consume, the amount of materials recycled by include urbanization, building dams, and dissemination of invasive species.]  three schools). HS-LS4-6: [Clarification Statement: Emphasis is on designing solutions for  H: Extend M-level  to include the use of technology to a proposed problem related to threatened or endangered species, or to  monitor/solve problems/protect the environment. genetic variation of organisms for multiple species.] H-level graphs can be similar if not the same, but content should specifically use language around the use of technology to monitor or solve an environmental problem. Science High School | of human activities on climate change and other natural systems.  which people and communities protect the Earth's HS-LS2-7: Design, evaluate, and refine a solution for reducing the impacts  environment, including through the use of technology of human activities on the environment and biodiversity.  (progression from S08ESS3.3). HS-LS4-6: Create or revise a simulation to test a solution to mitigate adverse impacts of human activity on biodiversity.  Low (L), Medium (M), High (H) Parameters: | Identify which among simple/common choices is a | Identify and compare simple methods for local efforts (such as reducing, reusing, and recycling resources) to large- monitoring or reducing human impact on the Earth or scale geoengineering design solutions (such as altering global temperatures  environment (e.g., a graph comparing the amount of by making large changes to the atmosphere or ocean).]  trash three cities produce, the amount of water three |  |
| S11ETS1.1 | HS-ETS1-1 and HS-ETS1-2 | Oregon Science Standard 2022:   Oregon Alternate Academic Achievement Standard |  | qualitative and quantitative criteria and constraints for solutions  associated solutions that impact individuals and broader society that account for societal needs and wants.  (progression from S08ETS1.1, S08ETS1.2). HS-ETS1-2: Design a solution to a complex real-world problem by breaking it down into smaller, more manageable problems that  Low (L), Medium (M), High (H) Parameters: | Based on a simple problem that impacts an individual or small group (i.e., a family, group of friends), identify the problem, possible constraints, and solutions to the problem. | Based on a simple problem that impacts a broader community (i.e., a neighborhood, community, town, city, etc.) identify the problem, possible constraints, and solutions to the problem. | Based on a simple problem that impacts broader society (i.e., state, region, nation, global, culture, etc.) identify the problem, possible constraints, and solutions to the problem. Science High School |
| S11LFS1.2 | HS-LS1-2 | Oregon Science Standard 2022: Develop and use a model to  Oregon Alternate Academic Achievement Standard | Oregon Science Standard Clarifications/Assessment Boundary  from S08LFS1.3). 2022: [Clarification Statement: Emphasis is on functions at the organism  Low (L), Medium (M), High (H) Parameters: [Assessment Boundary: Assessment does not include interactions  H: Connect internal human body parts to their materials and and functions at the molecular or chemical reaction level.]  function (e.g., skeletal system/bones providing structure). Science High School | provide specific functions within multicellular organisms.  systems of living organisms, including that they are composed of different materials and have different functions (progression | Identify different external/internal parts/systems of the body movement in response to neural stimuli. An example of an  using simple terminology and diagrams. | Connect external human body parts to their materials and function of elastic tissue and smooth muscle to regulate and  function (e.g., legs providing walking/running movement, eyes deliver the proper amount of blood within the circulatory system.]   providing sight). |  |
| S11LFS1.5 | HS-LS1-5 | Oregon Science Standard 2022: Use a model to illustrate how  Oregon Alternate Academic Achievement Standard | [Clarification Statement: Emphasis is on illustrating inputs and  L: Recognize through simple pictures and diagrams  what a outputs of matter and the transfer and transformation of energy in  plant/tree/flower needs to grow (i.e., the correct answer being photosynthesis by plants and other photosynthesizing organisms.  light, water, or air vs. related materials that would not help it Examples of models could include diagrams, chemical equations,  grow - darkness, no water, no air, soda), while including the and conceptual models.]   term/role/description of photosynthesis. [Assessment Boundary:  Assessment does not include specific  M: Extend L-level by using simple representative diagrams to biochemical steps.]  compare the (potential) growth of a plant/tree/flower (if one is given light, water and/or air, and the other is not), while including the term/role/description of photosynthesis in questions about what would help the plant grow (comparisons between plants are acceptable). | energy.  and water to grow and create energy through a process called photosynthesis (progression from S08LFS1.6). Oregon Science Standard Clarifications/Assessment Boundary 2022:   Low (L), Medium (M), High (H) Parameters: |  |  | Extend M-level by incorporating diagrams of photosynthesis that include things like the Sun (or other light source), arrows that indicate flow of light energy to create food (sugars) for the plants to function and grow under different environmental conditions. Science High School |
| S11LFS1.7 | HS-LS1-7 | Oregon Science Standard 2022: Use a model to illustrate that  Oregon Alternate Academic Achievement Standard | Oregon Science Standard Clarifications/Assessment Boundary  Low (L), Medium (M), High (H) Parameters: [Clarification Statement: Emphasis is on the conceptual  and oxygen to survive and grow (e.g., Which do you need to understanding of the inputs and outputs of the process of cellular  grow?; What does the dog breathe?). [Assessment Boundary: Assessment should not include  provide "energy" to humans and animals. | food molecules and oxygen molecules are broken and the bonds in  need oxygen to breathe and break down food to grow and obtain new compounds are formed resulting in a net transfer of energy.  energy (progression from S08LFS1.7). | Questions are related to humans and animals needing food | Extend L-level to involve oxygen and/or food helping to | Extend M-level by incorporating graphical diagrams that respiration.]  involve the relative amount of energy or expected growth based on a given situation involving food and/or oxygen. Science High School |
| S11LFS2.2 | HS-LS2-2 and HS-LS2-1 | Oregon Science Standard 2022:   Oregon Alternate Academic Achievement Standard | HS-LS2-1: [Clarification Statement: Examples of mathematical  how change might affect an individual or group of living representations include finding the average, determining trends,  organisms (e.g., removing a forest/food source might decrease and using graphical comparisons of multiple sets of data.]  bird/mammal populations). [Assessment Boundary: Assessment is limited to provided data.]  H: Introduce and ask questions about the concept of biodiversity, HS-LS2-1: [Clarification Statement: Emphasis is on quantitative  including how it might change based on factors such as analysis and comparison of the relationships among  availability of and changes in resources (e.g., food, water, shelter, interdependent factors including boundaries, resources, climate,  habitat). and competition. Examples of mathematical comparisons could include graphs, charts, histograms, and population changes gathered from simulations or historical data sets.] [Assessment Boundary: Assessment does not include deriving mathematical equations to make comparisons.] Science High School | revise explanations based on evidence about factors affecting  affect living organisms, including biodiversity and populations of biodiversity and populations in ecosystems of different scales.  organisms in an ecosystem (progression from S08LFS2.1). HS-LS2-2: Use mathematical and/or computational representations to support explanations of factors that affect  Low (L), Medium (M), High (H) Parameters: | Identify various resources or environmental factors that individual or groups of living organisms need to Oregon Science Standard Clarifications/Assessment  grow/reproduce/sustain their population. | Extend L-level to involve simple changes in resources and |  |
| S11LFS2.6 | HS-LS2-6 | Oregon Science Standard 2022: Evaluate the claims, evidence,  Oregon Alternate Academic Achievement Standard | Oregon Science Standard Clarifications/Assessment Boundary 2022:   Low (L), Medium (M), High (H) Parameters: [Clarification Statement: Examples of changes in ecosystem  L: Questions involve interaction between living and non-living conditions could include modest biological or physical changes,  aspects of a given ecosystem (e.g., habitat, shelter, water). | maintain relatively consistent numbers and types of organisms in  organisms interact with other living and non-living ecosystem stable conditions, but changing conditions may result in a new  components and how such interactions may change under ecosystem.  different environmental conditions (progression from S08LFS2.2). |  | Extend L-level to involve interaction between living changes, such as volcanic eruption or sea level rise.]  organisms (e.g., predator-prey, competitive, mutually beneficial). | Extend M-level to involve a change to either non-living or living related interaction and what the result might be, including the development of new ecosystems (e.g., no water becomes a desert-like ecosystem; loss of habitat induces animals to move to new area or decrease in numbers; loss of predator results in an increase in prey population) - being careful to give enough detail so that student understands the context and interaction being targeted. Science High School |
| S11LFS3.2 | HS-LS3-2 | Oregon Science Standard 2022: Make and defend a claim based  Oregon Alternate Academic Achievement Standard | [Clarification Statement: Emphasis is on using data to support  animals, humans); correct answer should not be identical, and arguments for the way variation occurs.]   distractors should include different species. [Assessment Boundary: Assessment does not include the phases  M: Identify the offspring of a given living organism (i.e., plants, of meiosis or the biochemical mechanism of specific steps in the  animals, humans); correct answer should not be identical to process.]  distractor and should include variations of the same and different species. | (1) new genetic combinations through meiosis, (2) viable errors  produces offspring with similar though varied traits based on occurring during replication, and/or (3) mutations caused by  genetic and environmental factors (progression from environmental factors.  S08LFS3.2). Oregon Science Standard Clarifications/Assessment  Low (L), Medium (M), High (H) Parameters: | Identify the offspring of a living organism (i.e., plants, |  | Identify the offspring of a given living organism (i.e., plants, animals, humans); correct answer should not be identical, with distractor options including both same and different species, and questions can introduce concept/situations involving changing environmental factors/mutations (e.g., increased pollution might cause an unhealthy offspring or a deformity, a slow change in habitat might result in detrimental or beneficial traits). Science High School |
| S11LFS4.3 | HS-LS4-3 | Oregon Science Standard 2022: Apply concepts of statistics and  Oregon Alternate Academic Achievement Standard | [Clarification Statement: Emphasis is on analyzing shifts in  Low (L), Medium (M), High (H) Parameters: [Assessment Boundary: Assessment is limited to basic statistical  survival/reproduction) as compared to traits from other animals and graphical analysis. Assessment does not include allele  that are unrelated to target animal. | advantageous heritable trait tend to increase in proportion to  have traits that help them survive, and that those organisms with organisms lacking this trait.  advantageous traits are more likely to survive compared to organisms with less advantageous traits (progression from Oregon Science Standard Clarifications/Assessment  S08LFS4.4). Boundary 2022: | Identify simple traits of animals (that help them to support explanations.]   survive/reproduce, while specifically referring to | Extend L-level to include the function of traits related to a single animal/group of same animal (e.g., Which trait helps the giraffe reach food from the tops of trees?; Which trait helps the owl see prey in the dark?) among other traits of the target animal. | Extend M-level by involving issues of survival/reproduction (e.g., Which group of giraffes would survive/increase in number if...) given a certain set of traits in a certain environmental circumstance or setting (e.g., habitat with tall trees). For H-level, the traits need to be variations on the same trait - the crux being that the correct option should relate to having an advantage in the given circumstance.  M- and H-level may also involve similar traits across different animals (i.e., wings on birds, tails for balance, etc). Science High School |
| S11LFS4.4 | HS-LS4-4 | Oregon Science Standard 2022: Construct an explanation based  Oregon Alternate Academic Achievement Standard | [Clarification Statement: Emphasis is on using data to provide  involve an adaptation without using language that links the evidence for how specific biotic and abiotic differences in  featured adaptation to its purpose (e.g., Which shows the tusks ecosystems (such as ranges of seasonal temperature, long-term  of an elephant?; Which is the hand of this boy?) as compared to climate change, acidity, light, geographic barriers, or evolution of  other features of the organism or from a different organism. | populations.  which living organisms adapt to their environment. Oregon Science Standard Clarifications/Assessment  Low (L), Medium (M), High (H) Parameters: | Identify simple features of humans, animals, or plants that | Identify features of humans, animals, or plants that involve time, leading to adaptation of populations.]  an adaptation using language that links the featured adaptation to its purpose (e.g., The elephant uses its tusks for digging and sparring with other elephants. Which shows the elephants tusks?) as compared to other features of the target organism. | Identify a specific adaptation (i.e., body part, behavior) based on asking about its function (e.g., Which adaptation does the tiger use to hide in tall grass?; Which adaptation attracts bees to the flower?). Science High School |
| S11PHS1.2 | HS-PS1-2 | Oregon Science Standard 2022: Construct and revise an  Oregon Alternate Academic Achievement Standard | [Clarification Statement: Examples of chemical reactions could  L: Identify and compare simple physical properties (including include the reaction of sodium and chlorine, of carbon and  size, shape, hardness/softness, weight, mass, and density) of oxygen, or of carbon and hydrogen.]   common objects; and chemical property includes whether or not [Assessment Boundary:  Assessment is limited to chemical  a substance is flammable. | on the outermost electron states of atoms, trends in the periodic  properties before and after a physical/chemical change, and table, and knowledge of the patterns of chemical properties.  whether nor not a physical/chemical change has occurred (progression from S08PHS1.2). Oregon Science Standard Clarifications/Assessment Boundary 2022:   Low (L), Medium (M), High (H) Parameters: |  | Properties include all of those in L-level and involves reactions.]  analyzing properties after a physical/chemical change to a given substance, including the use of graphs and data tables of such properties. | Extend M-level to physical versus chemical changes, which has occurred, and simple results. Science High School |
| S11PHS1.3 | HS-PS1-3 | Oregon Science Standard 2022: Plan and conduct an  Oregon Alternate Academic Achievement Standard | [Clarification Statement: Emphasis is on understanding the  objects or materials by linking them to the properties of the strengths of forces between particles, not on naming specific  material or resources from which they are made (e.g., This chair intermolecular forces (such as dipole-dipole). Examples of  is made from hard wood. What property does the chair have?). [Assessment Boundary: Assessment does not include Raoult’s  of both the object or material, and the material or resource, from law calculations of vapor pressure.]  which common and everyday objects or materials come from. Clarification around ORExt test questions: M-level does not explicitly detail the property of the resource/material.  H-level questions require students to explicitly identify the shared property between the source material and object. Science High School | substances at the bulk scale to infer the strength of electrical  substances, including on the material/resources from which they forces between particles.  are made (progression from S08PHS1.3). Oregon Science Standard Clarifications/Assessment  Low (L), Medium (M), High (H) Parameters: | Identify different bulk properties of common and everyday | Identify different bulk properties of common and everyday materials (such as graphite). Examples of bulk properties of  objects or materials while linking them to the material or substances could include the melting point and boiling point,  resources from which they are made. | Identify the common (shared) physical or chemical property |
| S11PHS1.7 | HS-PS1-7 | Oregon Science Standard 2022: Use mathematical  Oregon Alternate Academic Achievement Standard | [Clarification Statement: Emphasis is on using mathematical  L: Recognize through pictures/diagrams when a material or an ideas to communicate the proportional relationships between  object is the same. [Assessment Boundary:  Assessment does not include complex  difference between L- and M-level questions is that mass (a chemical reactions.]  mathematical measurement) is introduced in the M-level. H- level introduces a physical change or chemical reaction. Science High School | mass, are conserved during a chemical reaction.  including during physical changes and chemical reactions (progression from S08PHS1.2). Oregon Science Standard Clarifications/Assessment Boundary 2022:   Low (L), Medium (M), High (H) Parameters: |  | Recognize through pictures/diagrams when the amount of translation of these relationships to the macroscopic scale using  matter (mass) of a given material/object is the same. | Recognize that the amount of matter (mass) is conserved scale. Emphasis is on assessing students’ use of mathematical  after a physical change or chemical reaction. thinking and not on memorization and rote application of problem-solving techniques.]   Clarification around ORExt test questions: The primary |
| S11PHS2.1 | HS-PS2-1 | Oregon Science Standard 2022: Analyze data to support the  Oregon Alternate Academic Achievement Standard | [Clarification Statement: Examples of data could include tables or  M: Qualitatively compare forces, mass, and changes in motion graphs of position or velocity as a function of time for objects  in various comparative situations. [Assessment Boundary: Assessment is limited to one-dimensional motion and to macroscopic objects moving at non-relativistic speeds.] Science High School | mathematical relationship among the net force on a macroscopic  the motion of objects are related and comparable (progression object, its mass, and its acceleration.  from S08PHS2.2). Oregon Science Standard Clarifications/Assessment  Low (L), Medium (M), High (H) Parameters: | Qualitatively link mass with force and motion. |  | Qualitatively and quantitatively compare forces, mass, and object rolling down a ramp, or a moving object being pulled by a  changes in motion using diagrams, graphs, or tables. constant force.] |
| S11PHS2.3 | HS-PS2-3 | Oregon Science Standard 2022: Apply scientific and engineering  Oregon Alternate Academic Achievement Standard | Oregon Science Standard Clarifications/Assessment Boundary  (progression from S08PHS2.2). 2022: [Clarification Statement: Examples of evaluation and refinement  Low (L), Medium (M), High (H) Parameters: [Assessment Boundary: Assessment is limited to qualitative  same object), would result in an increase (larger amount) or evaluations and/or algebraic manipulations.]  decrease (smaller amount) in the amount of force. | force on a macroscopic object during a collision.  on objects is comparable and alterable, and identify ways in which the amount of force can be decreased or minimized | Identify which object has the most/least force (e.g., two of an object from damage and modifying the design to improve it.  three different objects not moving, and one large/massive object Examples of a device could include a football helmet or a  moving or vice versa). | Identify, which among three options or scenarios (using the | Identify devices that would help or ways in which one might decrease/minimize the amount of force during an impact or collision. Science High School |
| S11PHS3.3 | HS-PS3-3 | Oregon Science Standard 2022: Design, build, and refine a  Oregon Alternate Academic Achievement Standard | Oregon Science Standard Clarifications/Assessment Boundary 2022:   Low (L), Medium (M), High (H) Parameters: [Clarification Statement: Emphasis is on both qualitative and  L: Recognize or identify different examples of energy relative quantitative evaluations of devices. Examples of devices could  to its source (i.e., Sun to heat energy, light bulb to light energy, include Rube Goldberg devices, wind turbines, solar cells, solar  radio to sound energy - Which shows an example of heat ovens, and generators. Examples of constraints could include use  energy?). [Assessment Boundary: Assessment for quantitative evaluations is  transfer". | energy into another form of energy.*  transferable and convertible, and identify examples of and ways in which such transfers occur (progression from S08PHS3.4). |  | Extend L-level to also involve language around "energy | Recognize examples of common everyday conversions of devices constructed with materials provided to students.]  energy (e.g., Which shows an example of converting the Sun’s energy to electricity?; Which object converts electricity to heat energy?). * This performance expectation integrates traditional science content with engineering through a practice or disciplinary core idea. Science High School |
| S11PHS3.4 | HS-PS3-4 | Oregon Science Standard 2022: Plan and conduct an  Oregon Alternate Academic Achievement Standard | Oregon Science Standard Clarifications/Assessment Boundary  temperature, including the tools used to measure temperature 2022:   (i.e., traditional/digital thermometers). [Clarification Statement: Emphasis is on analyzing data from  M: Recognize examples of heat transfer or changes in student investigations and using mathematical thinking to describe  temperature, and how such transfer might be the energy changes both quantitatively and conceptually.  minimized/maximized and measured (e.g., wearing a coat to stay Examples of investigations could include mixing liquids at  warm, heating up a pan of water using stove, measuring different initial temperatures or adding objects at different  temperature (changes) using a digital thermometer). [Assessment Boundary: Assessment is limited to investigations  diagrams, models, and graphs to show such transfer/change, based on materials and tools provided to students.]  whether in a given circumstance or over time. Science High School | energy when two components of different temperature are  energy) as a measure of how hot or cold matter is and that it is combined within a closed system results in a more uniform energy  transferable (progression from S11PHS3.4). distribution among the components in the system (second law of thermodynamics).  Low (L), Medium (M), High (H) Parameters: | Recognize that hot and cold are related to measures of |  | Recognize heat transfer and changes in temperature using |
| S11PHS4.1 | HS-PS4-1 and HS-PS4-5 | Oregon Science Standard 2022:   Oregon Alternate Academic Achievement Standard | HS-PS4-1: [Clarification Statement: Examples of data could  and data tables that show examples of waves traveling through or include electromagnetic radiation traveling in a vacuum and  interacting with various objects/media. glass, sound waves traveling through air and water, and seismic waves traveling through the Earth.] [Assessment Boundary:   L-level may, but does not have to, include comparisons to non- Assessment is limited to algebraic relationships and describing  waves. M- and H-levels introduce the manner in which waves those relationships qualitatively.]  travel and quantitative aspects of wave measurement. HS-PS4-5: [Clarification Statement: Examples could include solar cells capturing light and converting it to electricity; medical imaging; and communications technology.] [Assessment Boundary:  Assessments are limited to qualitative information. Assessments do not include band theory.] Science High School | regarding relationships among the frequency, wavelength, and  different types of waves qualitatively and quantitatively, speed of waves traveling in various media.  including how they travel (progression from S08PHS4.2). HS-PS4-5: Communicate technical information about how some technological devices use the principles of wave behavior and  Low (L), Medium (M), High (H) Parameters: | Identify and describe examples of waves qualitatively. | Identify, describe, or compare waves qualitatively (e.g., Which shows a wave being reflected?; Which wave has the Oregon Science Standard Clarifications/Assessment  largest wavelength?). | Identify, describe, or compare waves using diagrams, graphs, |
| S11PHS4.2 | HS-PS4-2 | Oregon Science Standard 2022: Evaluate questions about the  Oregon Alternate Academic Achievement Standard | Oregon Science Standard Clarifications/Assessment Boundary  Low (L), Medium (M), High (H) Parameters: [Clarification Statement: Examples of advantages could include  technology (e.g., desktop/laptop computers, smart phones, that digital information is stable because it can be stored reliably  tablets) as compared to objects devices that are unrelated (e.g., in computer memory, transferred easily, and copied and shared  Which shows a computer?; Which shows a laptop?). | information.  technology that store and transmit information. | Identify common types of digital storage/transmitting | Identify that digital technology stores and transmits security, and theft.]  information in various common ways (e.g., email, texting, picture transfer) as compared to other unrelated (i.e., non- electronic and non-digital) objects that do not. | Identify that digital devices store and transmit information in various common ways (e.g., email, texting, picture transfer) as compared to other electronic objects that do not, including other electronic/digital devices. Science High School Standards not Essentialized: Please refer to Oregon’s published content standards for the full description and context of these codes. HS-ESS1-2  HS-LS1-1  HS-PS1-1 HS-ESS1-3  HS-LS1-3  HS-PS1-4 HS-ESS1-5  HS-LS1-4  HS-PS1-5 HS-ESS1-6  HS-LS1-6  HS-PS1-6 HS-ESS2-2  HS-LS2-3  HS-PS1-8 HS-ESS2-3  HS-LS2-4  HS-PS2-2 HS-ESS2-4  HS-LS2-5  HS-PS2-4 HS-ESS2-6  HS-LS2-8  HS-PS2-5 HS-ESS2-7  HS-LS3-1  HS-PS2-6 HS-ESS3-2  HS-LS3-3  HS-PS3-1 HS-ESS3-6  HS-LS4-1  HS-PS3-2 HS-ETS1-3  HS-LS4-2  HS-PS3-5 HS-ETS1-4  HS-LS4-5  HS-PS4-3 HS-PS4-4 |

